#!/bin/bash

exec 2>&1

{{#if bind.database.first.cfg.local_only ~}}
MYSQL_IP=127.0.0.1
{{else ~}}
MYSQL_IP={{bind.database.first.sys.ip}}
{{/if ~}}

############# Connect to Database #############################
mysql_ready() {
    mysqladmin ping -h $MYSQL_IP -u {{bind.database.first.cfg.username}} -p{{bind.database.first.cfg.password}} > /dev/null 2>&1
}

if !(mysql_ready) then
     echo "waiting for mysql ..."
     exit 1
fi

mysql -h $MYSQL_IP -u {{bind.database.first.cfg.username}} -p{{bind.database.first.cfg.password}} -e "create database IF NOT EXISTS {{cfg.database_name}}"
mysql -h $MYSQL_IP -u {{bind.database.first.cfg.username}} -p{{bind.database.first.cfg.password}} -D {{cfg.database_name}} < {{pkg.path}}/database/schema.sql

# create mysql entry
mkdir {{pkg.path}}/bin
printf "#!/bin/bash\nmysql -h $MYSQL_IP -u {{bind.database.first.cfg.username}} -p{{bind.database.first.cfg.password}} \$@" >> {{pkg.path}}/bin/mysql.sh
printf "#!/bin/bash\nmysql -h $MYSQL_IP -u {{bind.database.first.cfg.username}} -p{{bind.database.first.cfg.password}} -D {{cfg.database_name}} < \$1" >> {{pkg.path}}/bin/mysql_load.sh

chmod +x {{pkg.path}}/bin/mysql.sh
chown hab:hab {{pkg.path}}/bin/mysql.sh

chmod +x {{pkg.path}}/bin/mysql_load.sh
chown hab:hab {{pkg.path}}/bin/mysql_load.sh

############# PROJECT SETUP #############################
echo "Copying source files"
cp -r {{pkg.path}}/static/* {{pkg.svc_data_path}}/.

mkdir -p {{pkg.svc_data_path}}/uploads
chown hab:hab {{pkg.svc_data_path}}/uploads

cp {{pkg.svc_config_path}}/database.conf {{pkg.svc_data_path}}/persistence/conf/persistence-conf.php

chmod +x {{pkg.svc_data_path}}
chown -RL hab:hab {{pkg.svc_data_path}}

############# NGINX SETUP #############################
mkdir -p {{pkg.svc_var_path}}/nginx
chown hab:hab {{pkg.svc_var_path}}

