<?php


// This file generated by Propel convert-props target on Fri Apr 10 20:08:30 2009
// from XML runtime conf file /home/lancewf/databaseCreator/persistence/runtime-conf.xml
return array (
  'propel' => 
  array (
    'datasources' => 
    array (
      'persistence' => 
      array (
        'adapter' => 'mysql',
        'connection' => 
        array (
          'phptype' => 'mysql',
          'database' => 'moneydata',
          'hostspec' => 'localhost',
          'username' => 'phpuser',
          'password' => 'uJvQadbYwcBc3W3J',
        ),
      ),
      'default' => 'persistence',
    ),
  ),
);