<?php

  // include base peer class
  require_once 'persistence/om/BaseBilltypePeer.php';

  // include object class
  include_once 'persistence/Billtype.php';


/**
 * Skeleton subclass for performing query and update operations on the 'billtype' table.
 *
 * user's itinerary
 *
 * This class was autogenerated by Propel on:
 *
 * Mon Mar  8 23:25:10 2010
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    persistence
 */
class BilltypePeer extends BaseBilltypePeer {

} // BilltypePeer
