<?php

require_once 'persistence/om/BasePurchase.php';


/**
 * Skeleton subclass for representing a row from the 'purchase' table.
 *
 * A ride on a itinerary
 *
 * This class was autogenerated by Propel on:
 *
 * Mon Mar  8 23:25:10 2010
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    persistence
 */
class Purchase extends BasePurchase {
	public function getDateObject()
	{
		$date = strtotime($this->getDate());
		
		return $date;
	}
	
    public function toJson()
    {
        $array_store = array ();
    
        $array_store["key"] = $this->getKey();
        $array_store["store"] = $this->getStore();
        $array_store["cost"] = (double)$this->getCost();
        $array_store["notes"] = (String)$this->getNotes();
        $array_store["billtypekey"] = (int)$this->getBilltypeKey();
        
        $array_store["dayofmonth"] = (int)$this->getDayOfMonth();
        $array_store["month"] = (int)$this->getMonth();
        $array_store["year"] = (int)$this->getYear();
    
        return json_encode($array_store);
    }
    
    public function getYear()
    {
    	$date = $this->getDateObject();
		
		return date("Y",$date);
    }
    
	/**
	 * Get the day of the month
	 * @return 
	 */
	public function getDayOfMonth()
	{
		$date = $this->getDateObject();
		
		return date("j",$date);
	}

	/**
	 * Get the month of the park
	 * @return 
	 */
	public function getMonth()
	{
		$date = $this->getDateObject();
		
		return date("n",$date);
	}
} // Purchase
