<?php

  // include base peer class
  require_once 'persistence/om/BasePurchasePeer.php';

  // include object class
  include_once 'persistence/Purchase.php';


/**
 * Skeleton subclass for performing query and update operations on the 'purchase' table.
 *
 * A ride on a itinerary
 *
 * This class was autogenerated by Propel on:
 *
 * Mon Mar  8 23:25:10 2010
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    persistence
 */
class PurchasePeer extends BasePurchasePeer 
{
	public function getStores($user)
	{
		$con = Propel::getConnection(PurchasePeer::DATABASE_NAME);
		
		$sql = "SELECT DISTINCT " . PurchasePeer::STORE . 
			" FROM " . PurchasePeer::TABLE_NAME . " WHERE " . 
			PurchasePeer::USER_ID . " = " . $user->getId() . " ORDER BY " .
			PurchasePeer::STORE . " ASC";
		
		$stmt = $con->createStatement();
    	$rs = $stmt->executeQuery($sql, ResultSet::FETCHMODE_NUM);
    
    	$stores = array();
    	while($rs->next()) 
    	{
    		$store = $rs->getString(1);
    		
    		$stores[] = $store;
    	}
  	    
  	    return $stores;
	}
} // PurchasePeer
